root: "http://localhost:8000"
endpoints:
  - path: "/"
    freq: 30.0
  - path: "/foo"
    freq: -1.0
  - path: "/bar"
    freq: -1.0
  - path: "/qaz"
    freq: -1.0
  - path: "/qux"
    freq: -1.0
  - path: "/foobar"
    freq: -1.0
